### ISSUE TITLE
Aider is in this array but is not a word recognized by the majority of English dictionaries

### ISSUE THREAD

**Issue by WordlePlayer** [words/an-array-of-english-words#15]
The word aider has been added to this array incorrectly.

User Titus closed this previously reported issue in error due to a wordnick.com reference that mentions the term, but Wordnic focuses on having the largest wordlist, contrary to the most correct word list.  In an effort to inflate Wordnic's word list it adds modifiers to words (in this case the suffix -er) to generate new terms, but that doesn't make them words as these modified terms are not in common use.

none of the following dictionaries have a definition for the term "aider" nor do they classify it as a modification of the word "aid":

https://www.merriam-webster.com/dictionary/aider
https://www.oxfordlearnersdictionaries.com/definition/english/first-aider?q=aider
https://www.dictionary.com/browse/aider
https://www.britannica.com/dictionary/eb/spelling/aider

Wordnic and Wiktionary both claim to reference the word from the Century dictionary which does not offer online word lookup, so cannot be verified at this time.  Neither Wordnic nor Wiktionary are curated to the same scrutiny of the above listed organizations.

**Comment by wooorm** [comment]
Hi again!

Seems you are new to open source: you can still comment on closed issues. For further reference, #14.

You seem to come here with Wordle and Wiktionary and some other contexts. But, you dislike different contexts such as Wordnick. This project is not about your particular contexts. This project is a copy of some file someone once made for Letterpress https://github.com/words/an-array-of-english-words#an-array-of-english-words. So that it can be used in JavaScript. I am sure there are many other words you dislike. And other words others dislike. And I am sure things are missing.

If you dislike this word or other words, you can remove it yourself:

```js
const words = require('an-array-of-english-words')

const wordsIDoNotLike = ['aider']

const word = 'blub'

const fine = words.includes(word) && !wordsIDoNotLike.includes(word)
```

You can also make a different project: you can make a GH account and publish to npm.

This project isn’t an arbiter of what words are English.

I answer here because otherwise nobody will. But I care very little.

**Comment by WordlePlayer** [comment]
I appreciate the feedback on how to remove words.  

While I do not use github often, I am familiar with ticket systems, and people using this code should be able to see its associated flaws without digging through a closed ticket archive for tickets that get marked resolved when they continue to cause issue.

Its not a matter of liking or not liking words, its about not making up words.  If this was listed as "An-array-of-english-words-and-other-made-up-words" then it would not be an issue.  Wordnik is not an authority on the english languarge, they are a list builder trying to build the largest list by whichever means possible.

Unfortunately, several java script games online are using this array as a reference, so I am trying to trace the game errors to their source so that they may be corrected and create a more enjoyable experience for everyone.  Thats fine if nobody answers the ticket, because then the ticket will be easily viewable as a flaw with the array instead of being mistaken as a resolved issue.

**Comment by wooorm** [comment]
Which games use this? How did you find out this package is used in them?

This package isn’t really the root of the “problem”. Our source is, as the readme says, Letterpress. Perhaps that’s from somewhere else too.

I am not particularly interested in getting into arguments about the English language. And thus making this project a source of truth. Perhaps @zeke has some opinions?

**Comment by zeke** [comment]
All words are made up!

As @wooorm mentioned, if you find this list to be too liberally sprinkled with "non-words", it's not for you.

If you want to open a PR that updates the README to give users a heads-up that these aren't all "according to Webster's" words, we would accept such a change.
